import { DEMO_VIDEO_ID, parseYouTubeId, buildEmbedUrl, demoMetrics } from './lib.js';
const $ = s => document.querySelector(s); const frame=$('#videoFrame'), message=$('#formMessage'), badge=$('#modeBadge'); let step=0,currentVideo=DEMO_VIDEO_ID;
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2400)}
function setVideo(id,{demo=false,start=0}={}){currentVideo=id;frame.src=buildEmbedUrl(id,start);$('#videoTitle').textContent=demo?'Product launch keynote — Demo':`YouTube video · ${id}`;badge.innerHTML=`<span></span>${demo?'Demo live':'Video loaded'}`;message.textContent=demo?'Demo mode uses simulated analytics and a public YouTube sample.':'Video embedded. Analytics remain simulated in PulseView V1.';message.classList.remove('error');localStorage.setItem('pulseview:lastVideo',id);toast(demo?'Demo mode ready':'Video loaded successfully')}
$('#videoForm').addEventListener('submit',e=>{e.preventDefault();const id=parseYouTubeId($('#videoUrl').value);if(!id){message.textContent='Enter a valid YouTube video, Short, live, or youtu.be URL.';message.classList.add('error');$('#videoUrl').focus();return}setVideo(id)});
$('#demoButton').addEventListener('click',()=>{$('#videoUrl').value='https://www.youtube.com/watch?v=M7lc1UVf-VE';setVideo(DEMO_VIDEO_ID,{demo:true})});
$('#refreshButton').addEventListener('click',()=>{const m=demoMetrics(++step);$('#viewerMetric').textContent=m.viewers;$('#engagementMetric').textContent=m.engagement;$('#sentimentMetric').textContent=m.sentiment;$('#watchMetric').textContent=m.watchTime;drawChart(step);toast('Pulse refreshed just now')});
document.querySelectorAll('[data-seconds]').forEach(b=>b.addEventListener('click',()=>{setVideo(currentVideo,{demo:currentVideo===DEMO_VIDEO_ID,start:Number(b.dataset.seconds)});frame.scrollIntoView({behavior:'smooth',block:'center'})}));
document.querySelectorAll('.nav-link').forEach(link=>link.addEventListener('click',()=>{document.querySelectorAll('.nav-link').forEach(x=>x.classList.toggle('active',x===link));$('#sidebar').classList.remove('open')}));
$('#menuButton').addEventListener('click',()=>$('#sidebar').classList.toggle('open'));
function theme(value){document.documentElement.dataset.theme=value;localStorage.setItem('pulseview:theme',value);requestAnimationFrame(()=>drawChart(step))} theme(localStorage.getItem('pulseview:theme')||(matchMedia('(prefers-color-scheme:light)').matches?'light':'dark'));$('#themeToggle').addEventListener('click',()=>theme(document.documentElement.dataset.theme==='dark'?'light':'dark'));
function drawChart(seed=0){const c=$('#momentumChart'),box=c.getBoundingClientRect(),r=Math.min(devicePixelRatio||1,2);c.width=Math.max(1,box.width*r);c.height=Math.max(1,box.height*r);const x=c.getContext('2d');x.scale(r,r);const w=box.width,h=box.height,css=getComputedStyle(document.documentElement),border=css.getPropertyValue('--border').trim(),primary=css.getPropertyValue('--primary').trim(),cyan=css.getPropertyValue('--primary-2').trim();x.strokeStyle=border;x.lineWidth=1;for(let y=15;y<h;y+=42){x.beginPath();x.moveTo(0,y);x.lineTo(w,y);x.stroke()}const line=(data,color,fill)=>{const pts=data.map((v,i)=>({x:i/(data.length-1)*w,y:h-12-(v+Math.sin(i+seed)*2)/130*(h-28)}));x.beginPath();pts.forEach((p,i)=>i?x.lineTo(p.x,p.y):x.moveTo(p.x,p.y));x.lineWidth=2;x.lineJoin='round';x.strokeStyle=color;x.stroke();if(fill){x.lineTo(w,h);x.lineTo(0,h);x.closePath();const g=x.createLinearGradient(0,0,0,h);g.addColorStop(0,`${color}28`);g.addColorStop(1,`${color}00`);x.fillStyle=g;x.fill()}};line([28,31,29,39,42,47,44,57,61,58,70,76,72,84,88,94,92,103,111,108,121],primary,true);line([20,24,22,27,31,29,36,39,35,43,48,46,51,57,54,63,67,65,73,76,82],cyan,false)}
addEventListener('resize',()=>drawChart(step));requestAnimationFrame(()=>drawChart());if('serviceWorker'in navigator&&location.protocol!=='file:')addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
